<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-KQLETV0" failures="1" tests="11" name="AppiumChromeTest.AllTest" time="300.100" errors="0" timestamp="2023-05-31T11:33:47 CLT" skipped="0">
  <testcase classname="AppiumChromeTest.AllTest" name="testLogin" time="17.271"/>
  <testcase classname="AppiumChromeTest.AllTest" name="testLoginEmpty" time="11.914"/>
  <testcase classname="AppiumChromeTest.AllTest" name="testLoginWrong" time="12.964"/>
  <testcase classname="AppiumChromeTest.AllTest" name="searchTestAuto" time="15.452"/>
  <testcase classname="AppiumChromeTest.AllTest" name="searchTestDept" time="14.185"/>
  <testcase classname="AppiumChromeTest.AllTest" name="publicarTest" time="39.869"/>
  <testcase classname="AppiumChromeTest.AllTest" name="publicarInvalidTest1" time="38.740"/>
  <testcase classname="AppiumChromeTest.AllTest" name="publicarInvalidTest2" time="41.679"/>
  <testcase classname="AppiumChromeTest.AllTest" name="publicarInvalidTest3" time="39.128"/>
  <testcase classname="AppiumChromeTest.AllTest" name="comprarTest" time="35.663">
    <failure message="expected [https://compra.yapo.cl/checkouts/c/365101a5f919eef90f43fcc85f697322/shipping] but found [https://compra.yapo.cl/checkouts/c/7ecc3ebef3e6e3dabc68039d8e9b6b47/shipping]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://compra.yapo.cl/checkouts/c/365101a5f919eef90f43fcc85f697322/shipping] but found [https://compra.yapo.cl/checkouts/c/7ecc3ebef3e6e3dabc68039d8e9b6b47/shipping]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at AppiumChromeTest.AllTest.comprarTest(AllTest.java:244)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
    </failure>
  </testcase> <!-- comprarTest -->
  <testcase classname="AppiumChromeTest.AllTest" name="comprarWrongTest" time="33.235"/>
</testsuite> <!-- AppiumChromeTest.AllTest -->
